spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_CONFIG_NAMESPACE:dev}
        group: CLOUD_DEV_GROUP
pagehelper:
  helper-dialect: mysql
  reasonable: true # 启用合理化分页（如果当前页大于总页数，则返回最后一页）
  supportMethodsArguments: true # 支持通过Mapper接口方法参数来传递分页参数


gj:
  user:
    locked-max-minutes: 5
    max-failed-login-attempts: 3
